export const types = {
	SET_BUTTON_STATE: 'SET_BUTTON_STATE',
	SET_CIPHER_VAL: 'SET_CIPHER_VAL',
	SET_MATCHES: 'SET_MATCHES',
	SET_PROCESSED_STRING: 'SET_PROCESSED_STRING',
	SET_QUERY_STRING: 'SET_QUERY_STRING',
	SET_QUERY_VAL: 'SET_QUERY_VAL',
	SET_RESULTS_PANE_STATE: 'SET_RESULTS_PANE_STATE',
	SET_TOTAL_SUM: 'SET_TOTAL_SUM'
}